import Footer from "../components/Footer";
import Header from "../components/Header";
import styles from '../styles/Ssg.module.css'


function StaticSiteGeneration({ date }) {
  return ( 
    <>
      <Header/>
      <div className={styles.pageWrapper}>
        <div className={styles.pageContent}>
          <div className={styles.mainContent}>
            <h1 className="bold">Page Generated by <span className="blue">SSG</span> method</h1>
            <h4 className="bold">{date}</h4>
            <p>refresh to see the changes</p>
            <h6>This page was generated using the <span className="red">SSG (Static Site Generation)</span>  method, which means the page&apos;s HTML was <span className="red">generated at build time</span> by the Next.js aplication</h6>
            <h6>When a user requests the page, <span className="red">the app serves the already generated page</span>. This makes the HTML page generate <span className="red">just once</span>.</h6>
          </div>
        </div>
      </div>
      <Footer />
    </>
   );
}

export async function getStaticProps() {

  const date = new Date().toISOString()

  return {
    props: {
      date: date,
    },
  }
}

export default StaticSiteGeneration;